Feature/postgres sequence sql alchemy
ONSdigital/sdx-sequence pull request #17
Opened 2017-04-27 14:13 UTC by warrenbailey

Converting from a mongo sequence to a Postgres sequence. Using Flask-SQLAlchemy to interact with the database as it manages connection pools etc.

2017-04-27 16:00 UTC, eldeal commented on settings.py
> +DB_HOST = os.getenv('POSTGRES_HOST', '127.0.0.1')
As we're moving away from default values, this probably shouldn't have defaults.

2017-04-28 06:55 UTC, warrenbailey commented on settings.py
> +DB_HOST = os.getenv('POSTGRES_HOST', '127.0.0.1')
Good point, i'll remove

2017-04-28 14:32 UTC, warrenbailey commented on tests/test_server.py
> +        self.assertTrue(sequence_no >= sequence_start, "Sequence should be great than 1000 was {}".format(sequence_no))
Copy and paste error in these assert messages

2017-05-02 07:38 UTC, eldeal commented on server.py
> +        logger.debug("Database sequence no is: {}".format(sequence_no))
Would be preferable to have a separate KV par for the sequence_no - something like 'Retrieved sequence number', sequence_no=sequence_no' possibly

2017-05-02 07:39 UTC, eldeal commented on server.py
> +        logger.fatal("Failed to connect to database")
Is it possible to log out the headline of the error as a KV pair? Or the full traceback if we can't just get a portion of it.

2017-05-02 08:12 UTC, warrenbailey commented on server.py
> +        logger.fatal("Failed to connect to database")
Done

2017-05-02 08:12 UTC, warrenbailey commented on server.py
> +        logger.fatal("Failed to connect to database")
Done

2017-05-02 08:12 UTC, warrenbailey commented on server.py
> +        logger.debug("Database sequence no is: {}".format(sequence_no))
Done

2017-05-02 11:57 UTC, eldeal reviewed
LGTM for monitoring but should probably have a python 👍

2017-05-02 14:25 UTC, tundish requested changes

2017-05-02 14:25 UTC, tundish commented on settings.py
> +    logger.fatal("Unable to start service - DB connection details not set")
I can see _critical_ and _error_ are logger methods [in the structlog API](http://structlog.readthedocs.io/en/stable/api.html) but no mention of _fatal_.

2017-05-02 14:25 UTC, tundish commented on tests/test_sequence.py
Is it possible to create a text fixture with the sequences having the ranges defined from _schema.sql_? Then we could test for valid ranges, etc.

2017-05-02 15:03 UTC, warrenbailey commented on settings.py
> +    logger.fatal("Unable to start service - DB connection details not set")
Good spot, I thought I'd changed that. I'll correct.

2017-05-02 15:03 UTC, warrenbailey commented on tests/test_sequence.py
Yes will add

2017-05-02 15:17 UTC, necrophonic commented on .travis.yml
> +   postgresql: "9.4"
`9.4`?

2017-05-02 15:17 UTC, necrophonic commented on README.md
> +POSTGRES_PASSWORD="sdx"
Should be in the environment var block at the bottom. Also, the readme still talks about the MongoDB which no longer exists in this world!

2017-05-02 15:17 UTC, necrophonic commented on schema.sql
> +CREATE SEQUENCE sequence MINVALUE 1000 MAXVALUE 9999 CYCLE;
Should maybe live under a `setup` or similar sub folder as it's only relevant to the initial environmental configuration rather than the actual running of the service.

2017-05-02 15:17 UTC, necrophonic commented on settings.py
> +LOGGING_FORMAT = "%(message)s"
Does this format change have an impact on the splunk collection?

2017-05-02 15:17 UTC, necrophonic commented on tests/__init__.py
> +os.environ['POSTGRES_PASSWORD'] = os.getenv("POSTGRES_PASSWORD", "sdx")
Shouldn't be putting defaults into env vars now

2017-05-03 07:05 UTC, warrenbailey commented on .travis.yml
> +   postgresql: "9.4"
For some reason, Travis didn't like 9.6. I'll try again and confirm the error

2017-05-03 07:08 UTC, eldeal commented on settings.py
> +LOGGING_FORMAT = "%(message)s"
It's the preferable format for Splunk as it'll be JSON. There might be an issue with getting Splunk to recognize JSON in one case and the old format for other services simultaneously, I'm checking on that this morning. May have to revert the change sorry! :/

2017-05-03 07:26 UTC, necrophonic commented on .travis.yml
> +   postgresql: "9.4"
Think we had a similar issue before. 9.6 should be available (https://docs.travis-ci.com/user/database-setup/#PostgreSQL) but you may have to specify the Linux container.

2017-05-03 07:29 UTC, eldeal commented on settings.py
> +LOGGING_FORMAT = "%(message)s"
Question answered - we think it's possible for Splunk to deal with both, so this is totally fine and I'll put something on the cards to get the config updated 👍

2017-05-03 08:40 UTC, warrenbailey commented on tests/__init__.py
> +os.environ['POSTGRES_PASSWORD'] = os.getenv("POSTGRES_PASSWORD", "sdx")
Removed and using a testing.postgres in-memory database instead

2017-05-03 08:40 UTC, warrenbailey commented on schema.sql
> +CREATE SEQUENCE sequence MINVALUE 1000 MAXVALUE 9999 CYCLE;
Done

2017-05-03 08:44 UTC, warrenbailey commented
I need to rename the Postgres variables so that they are unique to sdx-sequence. Also need to up travis version of postgres to 9.6

2017-05-03 09:17 UTC, warrenbailey commented on .travis.yml
> +   postgresql: "9.4"
I don't actually need it now I've switched to an in memory postgres DB for testing

2017-05-04 15:58 UTC, JamesGardiner requested changes

2017-05-04 15:58 UTC, JamesGardiner commented on server.py
> +import psycopg2
Imports should be PEP8 compliant.

2017-05-04 15:58 UTC, JamesGardiner commented on settings.py
> +LOGGING_FORMAT = "%(message)s"
Can this be changed to:

```python
LOGGING_FORMAT = "{}".format(message)
```

which is the preferred string formatting method for modern Python.

2017-05-04 15:58 UTC, JamesGardiner commented on settings.py
> +        raise ValueError("No value set for " + key)
`No value set for {}".format(key)`

2017-05-04 15:58 UTC, JamesGardiner commented on settings.py
> +except ValueError as e:
Can the value error that was thrown be logged as well - underrstanding which envvar is missing would help.

2017-05-04 15:58 UTC, JamesGardiner commented on tests/__init__.py
> +import settings
Imports should be PEP8 compliant

2017-05-05 08:27 UTC, warrenbailey commented on settings.py
> +except ValueError as e:
It is logged in the _get_value function if it's missing :)

2017-05-05 08:29 UTC, warrenbailey commented on settings.py
> +        raise ValueError("No value set for " + key)
Done

2017-05-05 11:56 UTC, JamesGardiner approved these changes

2017-05-05 12:53 UTC, tundish approved these changes

2017-05-08 12:35 UTC, necrophonic approved these changes

2017-05-08 12:48 UTC, merged