Add functionality for sdx-common with new logger formatting
ONSdigital/sdx-sequence pull request #22
Opened 2017-06-08 08:23 UTC by gavinleeedwards

2017-06-08 09:38 UTC, JamesGardiner requested changes

2017-06-08 09:38 UTC, JamesGardiner commented on README.md
> +Using virtualenv and pip, create a new environment and install the sdx-common library from a local directory:
Can we change this so that it shows the use of the makefile? Look at sdx-receipt-ctp for an example.

2017-06-09 13:44 UTC, warrenbailey requested changes

2017-06-09 13:44 UTC, warrenbailey commented on server.py
> +logger_initial_config(service_name='sdx-sequence')
I think you've lost the log level here?

See https://github.com/ONSdigital/sdx-receipt-rrm/pull/37/files

2017-06-09 13:56 UTC, warrenbailey submitted a review, later dismissed

2017-06-09 13:58 UTC, JamesGardiner requested changes
README still needs to be updated to show use of `make` instead of `pip`

2017-06-09 14:20 UTC, JamesGardiner approved these changes

2017-06-09 14:20 UTC, merged