Remove sdx-common clone in docker
ONSdigital/sdx-sequence pull request #42
Opened 2017-09-14 07:22 UTC by emilioward

## What? and Why?
> What does this pull request change/fix? Why was it necessary?

This PR fixes the issue of a cryptography error when running docker build in sdx-sequence

## Checklist
  - [x] CHANGELOG.md updated? (if required)

2017-09-14 07:33 UTC, gemmai95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Remove sdx common clone in Dockerfiles](https://trello.com/c/AfHeYs4M/400-3-remove-sdx-common-clone-in-dockerfiles)

2017-09-14 11:11 UTC, necrophonic requested changes

2017-09-14 11:11 UTC, necrophonic commented on Dockerfile
> +FROM onsdigital/flask-crypto-queue
Why change to the queue version? `sdx-sequence` shouldn't be needing queue functionality?

2017-09-14 11:11 UTC, necrophonic commented on Dockerfile
>  ENTRYPOINT ./startup.sh
Container doesn't start:
```
[2017-09-14 11:10:03 +0000] [11] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.4/dist-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/app/server.py", line 13, in <module>
    from sequences import sequence, batch_sequence, image_sequence, json_sequence
ImportError: No module named 'sequences'
[2017-09-14 11:10:03 +0000] [11] [INFO] Worker exiting (pid: 11)
[2017-09-14 11:10:03 +0000] [8] [INFO] Shutting down: Master
[2017-09-14 11:10:03 +0000] [8] [INFO] Reason: Worker failed to boot.
```

2017-09-15 09:16 UTC, gemmai95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Remove sdx common clone in Dockerfiles](https://trello.com/c/AfHeYs4M/400-3-remove-sdx-common-clone-in-dockerfiles)

2017-09-15 10:18 UTC, emilioward commented on Dockerfile
>  ENTRYPOINT ./startup.sh
Issue has now been addressed 👍

2017-09-20 11:16 UTC, JamesGardiner approved these changes

2017-09-20 13:59 UTC, dcdarrell9 approved these changes
LGTM 👍

2017-09-21 08:12 UTC, necrophonic approved these changes

2017-09-21 08:23 UTC, merged