Fix logging and security issues
ONSdigital/sdx-sequence pull request #59
Opened 2019-02-14 16:29 UTC by insacuri

## What? and Why?
sdx-sequence logs its lines in the following way 
```
sdx-sequence_1               | --------------------------------------------------------------------------------
sdx-sequence_1               | DEBUG in _base [/usr/local/lib/python3.6/site-packages/structlog/_base.py:177]:
sdx-sequence_1               | 2019-02-14 15:57.34 Connection successful
sdx-sequence_1               | --------------------------------------------------------------------------------
```

they should look like 
`sdx-sequence_1               | 2019-02-14T16:10:28.000279Z|DEBUG: sdx-sequence: 2019-02-14 16:10.28 Connection successful`

## Checklist
  - [x] CHANGELOG.md updated? (if required)

2019-02-15 09:41 UTC, ryangrundy7 requested changes
Still getting the old style logging when calling `http://localhost:8086/healthcheck`

2019-02-15 10:13 UTC, ryangrundy7 submitted a review, later dismissed
Logging looks good now and no security issues as far as I can see 👍

2019-02-15 10:36 UTC, ryangrundy7 approved these changes

2019-02-18 13:13 UTC, mfcrocker approved these changes

2019-02-18 13:29 UTC, merged